


coverage:
  precision: 2
  round: down
  range: "60...90"
  
  status:
    project:
      default:
        target: 70%
        threshold: 5%
        if_ci_failed: error
    patch:
      default:
        target: 70%
        threshold: 5%

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true
  require_base: false
  require_head: true

flags:
  backend:
    paths:
      - backend/
    carryforward: true
  frontend:
    paths:
      - frontend/
    carryforward: true

ignore:
  - "**/test/**"
  - "**/tests/**"
  - "**/*Test.java"
  - "**/*Tests.java"
  - "**/*IT.java"
  - "**/*.spec.ts"
  - "**/e2e/**"
  - "**/cypress/**"
  - "**/node_modules/**"
  - "**/target/**"
  - "**/dist/**"
  - "**/*.config.*"
  - "**/setup-jest.ts"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no
