name: CI + Tools
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch: {} # Manual trigger for the "Tool – Angular Latest Upgrade PR" job

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # =============== PATH DETECT (Find everything in one place) ===============
  detect-paths:
    name: Detect project paths
    runs-on: ubuntu-latest
    outputs:
      FRONT_DIR: ${{ steps.out.outputs.FRONT_DIR }}
      FRONT_IS_ANGULAR: ${{ steps.out.outputs.FRONT_IS_ANGULAR }}
      JAVA_DIR: ${{ steps.out.outputs.JAVA_DIR }}
      NODE_DIR: ${{ steps.out.outputs.NODE_DIR }}
    steps:
      - uses: actions/checkout@v4
      - id: out
        run: |
          # --- Find frontend: prefer 'frontend/', otherwise any angular.json ---
          FRONT_DIR=""
          if [ -f frontend/package.json ]; then
            FRONT_DIR="frontend"
          else
            hit="$(find . -maxdepth 3 -type f -name angular.json | head -n1 || true)"
            if [ -n "$hit" ]; then
              FRONT_DIR="$(dirname "$hit" | sed 's|^\./||')"
            fi
          fi

          FRONT_IS_ANGULAR="false"
          if [ -n "$FRONT_DIR" ] && [ -f "$FRONT_DIR/package.json" ]; then
            HAS_NG=$(node -p "p=require('./$FRONT_DIR/package.json');(p.dependencies&&p.dependencies['@angular/core'])||(p.devDependencies&&p.devDependencies['@angular/core'])? 'true':'false'" || echo "false")
            FRONT_IS_ANGULAR="$HAS_NG"
          fi

          # --- Find Java backend: prefer 'backend/', then 'api/', then any pom.xml ---
          JAVA_DIR=""
          if [ -f backend/pom.xml ]; then
            JAVA_DIR="backend"
          elif [ -f api/pom.xml ]; then
            JAVA_DIR="api"
          else
            hit="$(find . -maxdepth 3 -type f -name pom.xml | head -n1 || true)"
            if [ -n "$hit" ]; then
              JAVA_DIR="$(dirname "$hit" | sed 's|^\./||')"
            fi
          fi

          # --- Find Node backend: prefer 'backend/' or 'api/' with package.json (if no pom.xml exists there) ---
          NODE_DIR=""
          if [ -f backend/package.json ] && [ ! -f backend/pom.xml ]; then
            NODE_DIR="backend"
          elif [ -f api/package.json ] && [ ! -f api/pom.xml ]; then
            NODE_DIR="api"
          else
            hit="$(find . -maxdepth 3 -type f -name package.json | grep -Ev '^\.\/(node_modules|frontend|web|dist|build)\/' | head -n1 || true)"
            if [ -n "$hit" ]; then
              d="$(dirname "$hit" | sed 's|^\./||')"
              if [ ! -f "$d/pom.xml" ]; then NODE_DIR="$d"; fi
            fi
          fi

          echo "FRONT_DIR=$FRONT_DIR" >> $GITHUB_OUTPUT
          echo "FRONT_IS_ANGULAR=$FRONT_IS_ANGULAR" >> $GITHUB_OUTPUT
          echo "JAVA_DIR=$JAVA_DIR" >> $GITHUB_OUTPUT
          echo "NODE_DIR=$NODE_DIR" >> $GITHUB_OUTPUT

  # =============== BACKEND: JAVA (MAVEN) ===============
  backend-java:
    name: Backend (Java/Maven)
    needs: [detect-paths]
    runs-on: ubuntu-latest
    if: ${{ needs.detect-paths.outputs.JAVA_DIR != '' }}
    steps:
      - uses: actions/checkout@v4
      - id: jd
        run: |
          cd "${{ needs.detect-paths.outputs.JAVA_DIR }}"
          JAVA=17
          if grep -Eq '<maven\.compiler\.release>21</maven\.compiler\.release>|<maven\.compiler\.(source|target)>21</maven\.compiler\.(source|target)>' pom.xml; then
            JAVA=21
          fi
          echo "java=$JAVA" >> $GITHUB_OUTPUT
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ steps.jd.outputs.java }}
          cache: maven
      - name: Build (skip tests for stability)
        run: |
          cd "${{ needs.detect-paths.outputs.JAVA_DIR }}"
          mvn -B -q -DskipTests -DskipITs -Dmaven.test.skip=true clean package || mvn -B -q -DskipTests clean package

  # =============== BACKEND: NODE / EXPRESS ===============
  backend-node:
    name: Backend (Node/Express)
    needs: [detect-paths]
    runs-on: ubuntu-latest
    if: ${{ needs.detect-paths.outputs.NODE_DIR != '' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: ${{ needs.detect-paths.outputs.NODE_DIR }}/package-lock.json
      - name: Install
        run: |
          cd "${{ needs.detect-paths.outputs.NODE_DIR }}"
          npm ci || npm ci --legacy-peer-deps
      - name: Lint (best-effort)
        run: |
          cd "${{ needs.detect-paths.outputs.NODE_DIR }}"
          npm run lint --if-present || echo "No lint or failed — continuing."
      - name: Build (best-effort)
        run: |
          cd "${{ needs.detect-paths.outputs.NODE_DIR }}"
          npm run build --if-present || echo "No build script — continuing."
      - name: Test (best-effort)
        run: |
          cd "${{ needs.detect-paths.outputs.NODE_DIR }}"
          npm test --if-present || echo "No tests or failed — continuing."

  # =============== FRONTEND: ANGULAR / GENERIC ===============
  frontend:
    name: Frontend
    needs: [detect-paths]
    runs-on: ubuntu-latest
    if: ${{ needs.detect-paths.outputs.FRONT_DIR != '' }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: ${{ needs.detect-paths.outputs.FRONT_DIR }}/package-lock.json

      # Check for Angular and its version
      - id: ngver
        run: |
          cd "${{ needs.detect-paths.outputs.FRONT_DIR }}"
          HAS_NG=$(node -p "p=require('./package.json');(p.dependencies&&p.dependencies['@angular/core'])||(p.devDependencies&&p.devDependencies['@angular/core'])? 'yes':'no'" || echo "no")
          CORE_VER=""
          BUILD_VER=""
          CORE_MAJ=0
          BUILD_MAJ=0
          if [ "$HAS_NG" = "yes" ]; then
            CORE_VER=$(node -p "p=require('./package.json');(p.dependencies?.['@angular/core']||p.devDependencies?.['@angular/core']||'')" || echo "")
            BUILD_VER=$(node -p "p=require('./package.json');(p.devDependencies?.['@angular-devkit/build-angular']||p.devDependencies?.['@angular/build']||'')" || echo "")
            CORE_MAJ=$(echo "$CORE_VER" | sed -E 's/[^0-9]*([0-9]+).*/\1/'); [ -z "$CORE_MAJ" ] && CORE_MAJ=0
            BUILD_MAJ=$(echo "$BUILD_VER" | sed -E 's/[^0-9]*([0-9]+).*/\1/'); [ -z "$BUILD_MAJ" ] && BUILD_MAJ=0
          fi
          echo "HAS_NG=$HAS_NG" >> $GITHUB_OUTPUT
          echo "CORE_MAJ=$CORE_MAJ" >> $GITHUB_OUTPUT
          echo "BUILD_MAJ=$BUILD_MAJ" >> $GITHUB_OUTPUT

      # Get latest Angular version from NPM
      - name: Get latest Angular version
        if: ${{ steps.ngver.outputs.HAS_NG == 'yes' }}
        id: nglatest
        run: |
          LATEST_VER=$(npm view @angular/core version)
          LATEST_MAJ=$(echo "$LATEST_VER" | sed 's/\..*//')
          echo "LATEST_VER=$LATEST_VER" >> $GITHUB_OUTPUT
          echo "LATEST_MAJ=$LATEST_MAJ" >> $GITHUB_OUTPUT

      # If Angular and version mismatch -> auto-upgrade to latest
      - name: Auto-upgrade Angular to latest (only if Angular)
        if: ${{ steps.ngver.outputs.HAS_NG == 'yes' && steps.nglatest.outputs.LATEST_MAJ != '' && (fromJSON(steps.ngver.outputs.CORE_MAJ) < fromJSON(steps.nglatest.outputs.LATEST_MAJ)) }}
        run: |
          cd "${{ needs.detect-paths.outputs.FRONT_DIR }}"
          echo "Upgrading Angular CLI and Core to @latest using 'ng update'..."
          
          # First, ensure a clean install of the current state so 'ng update' has a baseline
          npm ci --legacy-peer-deps
          
          # Let ng update handle the package updates and code migrations together. This is the official, robust way.
          npx ng update @angular/cli@latest @angular/core@latest --force --allow-dirty

      - name: Install deps (tolerant)
        run: |
          cd "${{ needs.detect-paths.outputs.FRONT_DIR }}"
          npm ci || npm ci --legacy-peer-deps

      - name: Build (Angular or generic)
        run: |
          cd "${{ needs.detect-paths.outputs.FRONT_DIR }}"
          if [ -f angular.json ] && [ "${{ steps.ngver.outputs.HAS_NG }}" = "yes" ]; then
            # If the build script already contains --configuration=..., don't add it again
            if node -e "p=require('./package.json');process.exit((p.scripts&&p.scripts.build||'').includes('--configuration=')?0:1)"; then
              npm run build
            else
              npm run build -- --configuration=production
            fi
          else
            npm run build --if-present || echo "No non-Angular build script — skipping."
          fi

      - name: Optional tests (best-effort)
        run: |
          cd "${{ needs.detect-paths.outputs.FRONT_DIR }}"
          npm run test --if-present -- --watch=false --browsers=ChromeHeadless --no-sandbox || echo "Skipping tests."

  # =============== TOOL: Manual Angular Latest Upgrade PR ===============
  upgrade-angular-latest:
    name: Tool – Angular Latest Upgrade PR
    needs: [detect-paths]
    if: ${{ github.event_name == 'workflow_dispatch' && needs.detect-paths.outputs.FRONT_DIR != '' && needs.detect-paths.outputs.FRONT_IS_ANGULAR == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Get latest Angular core version for PR title
        id: nglatest
        run: |
          LATEST_VER=$(npm view @angular/core version)
          echo "LATEST_VER=$LATEST_VER" >> $GITHUB_OUTPUT

      - name: Upgrade in detected frontend
        run: |
          cd "${{ needs.detect-paths.outputs.FRONT_DIR }}"
          echo "Upgrading Angular CLI and Core to @latest using 'ng update'..."
          
          # First, ensure a clean install of the current state so 'ng update' has a baseline
          npm ci --legacy-peer-deps
          
          # Let ng update handle the package updates and code migrations together. This is the official, robust way.
          npx ng update @angular/cli@latest @angular/core@latest --force --allow-dirty

          if [ -f angular.json ]; then npm run build -- --configuration=production; fi
      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        with:
          branch: chore/angular-latest
          title: "chore(frontend): upgrade Angular to latest (v${{ steps.nglatest.outputs.LATEST_VER }})"
          commit-message: "chore(frontend): upgrade Angular packages to latest"
          body: |
            Automated Angular upgrade to latest versions in `${{ needs.detect-paths.outputs.FRONT_DIR }}`:
            - All @angular/* packages -> @latest
            - @angular-devkit/build-angular -> @latest
            - Build verified
          labels: dependencies, angular
