name: CI
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  backend-java:
    name: Backend (Java/Maven)
    runs-on: ubuntu-latest
    if: ${{ hashFiles('backend/pom.xml') != '' }}
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven
      - name: Build & Test (Maven)
        run: mvn -B -q clean verify

  backend-node:
    name: Backend (Node/Express)
    runs-on: ubuntu-latest
    if: ${{ hashFiles('backend/package.json') != '' && hashFiles('backend/pom.xml') == '' }}
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: backend/package-lock.json
      - name: Install deps
        run: npm ci
      - name: Test (if present)
        run: npm test --if-present --silent
      - name: Lint (if present)
        run: npm run lint --if-present --silent
      - name: Build (if present)
        run: npm run build --if-present --silent

  frontend-angular:
    name: Frontend (Angular)
    runs-on: ubuntu-latest
    if: ${{ hashFiles('frontend/package.json') != '' }}
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: frontend/package-lock.json
      - name: Install deps
        run: npm ci
      - name: Test (if present)
        run: |
          npm run test --if-present -- --watch=false --browsers=ChromeHeadless || echo "No Angular tests or headless Chrome; skipping."
      - name: Build
        run: |
          if [ -f angular.json ]; then
            npm run build -- --configuration=production
          else
            npm run build --if-present
          fi
